version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/python:3.6.4
        environment:
          SECRET_KEY: abcd
    steps:
      - checkout
      - run: pipenv install --dev
      - run: pipenv run promgen test
      - run: pipenv run coverage html -d test-results
      - run: pipenv run codecov
      - store_test_results:
          path: test-results
