version: 2
jobs:
  build:
    docker:
      - image: python:3.5.3-alpine
        environment:
          SECRET_KEY: abcd
    steps:
      - checkout
      - run: pip install -e .[dev]
      - run: promgen test
      - run: coverage html -d $CIRCLE_ARTIFACTS
      - run: codecov

general:
  branches:
    ignore:
      - gh-pages
